name: LogicExtraPlotSquaredPlaceholders
version: '${project.version}'
main: net.anturnia.logicExtraPlotSquaredPlaceholders.Main
api-version: '1.20'
author: "FrinshHD"
depend:
  - PlotSquared
  - PlaceholderAPI
